"""Auditor integration on an AUTHENTIC Microsoft-hosted PBIT file.

The Power BI template is an actual published file rather than one generated by
our sample builder. The semantic-model contents may themselves be sample data;
we are validating static template parsing and reporting, not business figures.
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path
import requests
import zipfile

SOURCE="https://raw.githubusercontent.com/microsoft/powerbi-desktop-samples/main/powerbi-service-samples/COVID-19%20US%20Tracking%20Sample.pbit"

def audit(output="results/microsoft_pbit_real_file_audit.json"):
    res=requests.get(SOURCE,timeout=80)
    res.raise_for_status()
    if len(res.content)<25000 or not zipfile.is_zipfile(__import__("io").BytesIO(res.content)):
        raise ValueError("Actual remote Microsoft template is not a valid sizable PBIT zip archive")
    path=Path("/tmp/microsoft_real_powerbi_template.pbit")
    path.write_bytes(res.content)
    cmd=[sys.executable,"audit.py","--file",str(path),"--json"]
    proc=subprocess.run(cmd,capture_output=True,text=True,timeout=120)
    if proc.returncode not in (0,1):
        raise RuntimeError(f"Auditor failed to read actual template: exit={proc.returncode}: {proc.stderr[:1800]}")
    payload=json.loads(proc.stdout)
    summary={
        "source": SOURCE,
        "actual_file_bytes":len(res.content),
        "template_is_actual_microsoft_repo_file":True,
        "auditor_completed_and_parsed_file":True,
        "auditor_exit_code":proc.returncode,
        "audit_findings":payload,
        "interpreting_errors": "Exit 1 denotes actual structural findings in the public source template, not parser malfunction.",
        "not_verified": "Template data refresh, source dataset values and rendered Power BI visuals were not executed."
    }
    dest=Path(output);dest.parent.mkdir(parents=True,exist_ok=True)
    dest.write_text(json.dumps(summary,indent=2)+"\n")
    print(json.dumps({"source":SOURCE,"file_bytes":len(res.content),"auditor_exit":proc.returncode,"findings_keys":list(payload),"summary":payload.get("summary"),"findings_count":len(payload.get("findings",[]))},indent=2))
    return summary

def main():
    p=argparse.ArgumentParser();p.add_argument("--output",default="results/microsoft_pbit_real_file_audit.json")
    args=p.parse_args()
    audit(args.output)

if __name__=="__main__":
    main()
